# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAllele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='varianteffect',
            name='variant',
        ),
        migrations.AddField(
            model_name='variantallele',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster.Variant'),
        ),
        migrations.AddField(
            model_name='varianteffect',
            name='allele',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monster.VariantAllele'),
            preserve_default=False,
        ),
    ]
