# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0002_auto_20171203_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monstervariant',
            name='variant',
        ),
        migrations.AddField(
            model_name='monstervariant',
            name='allele',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monster.VariantAllele'),
            preserve_default=False,
        ),
    ]
