# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0003_auto_20171203_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
