# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0006_auto_20171204_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='institute_name',
            field=models.CharField(default='NA', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='scientist_name',
            field=models.CharField(default='NA', max_length=64),
            preserve_default=False,
        ),
    ]
