# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0007_auto_20171204_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_image',
            field=models.ImageField(null=True, upload_to='monsters/'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='record_image',
            field=models.ImageField(null=True, upload_to='monsters/'),
        ),
        migrations.AlterUniqueTogether(
            name='variantallele',
            unique_together=set([('variant', 'sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='varianteffect',
            unique_together=set([('gene', 'allele')]),
        ),
    ]
