# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0008_auto_20171204_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=64)),
            ],
        ),
    ]
