# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 11:31
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime


def add_default_se(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SequencingEvent = apps.get_model("monster", "SequencingEvent")
    s = SequencingEvent(name="DEFAULT", description="A catch-all event for all unassigned Sequencing Runs", date=datetime.now().date(), location="Monster Lab")
    s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0009_sequencingevent'),
    ]

    operations = [
            migrations.RunPython(add_default_se),
    ]
