# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0010_auto_20180614_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monster.SequencingEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
