# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0013_auto_20180614_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sequencingevent',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
