# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-23 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0015_sequencingevent_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencingevent',
            name='colour_bg',
            field=models.CharField(default='5cb85c', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencingevent',
            name='colour_fg',
            field=models.CharField(default='fff', max_length=10),
            preserve_default=False,
        ),
    ]
